### ISSUE TITLE
Access to and using Reddit API

### ISSUE THREAD

**Issue by adil1508** [adil1508/Dad-make-a-funny#6]
Need access to Reddit API to pull jokes from

**Comment by asilmian** [comment]
@adil1508 what format do you want the jokes to be in? Have a look at the Joke class in Dev_Asil branch. Will that be useable?

**Comment by adil1508** [comment]
I'll take a look at the new class. Basically what we want now is just the
text of a joke.

I guess it wouldn't hurt to have more details but we might scrap it if it's
at the expense of development time

**Comment by asilmian** [comment]
Reddit api completed. We have access to reddit and code is pulling jokes from dadjokes subreddit.
